name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build with zola
        uses: docker://ghcr.io/getzola/zola:v0.15.3
        with:
          entrypoint: /bin/zola
          args: build
      - name: Deploy built site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public/
          branch: rendered
